//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pee_Reviewer_00172097
{
    using System;
    using System.Collections.Generic;
    
    public partial class AuthorSkill
    {
        public int Id { get; set; }
        public Nullable<int> authorId { get; set; }
        public Nullable<int> skillId { get; set; }
    
        public virtual Author Author { get; set; }
        public virtual Skill Skill { get; set; }
    }
}
