//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pee_Reviewer_00172097
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Peer_ReviewrDBEntities : DbContext
    {
        public Peer_ReviewrDBEntities()
            : base("name=Peer_ReviewrDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Account> Accounts { get; set; }
        public virtual DbSet<Author> Authors { get; set; }
        public virtual DbSet<AuthorSkill> AuthorSkills { get; set; }
        public virtual DbSet<Comment> Comments { get; set; }
        public virtual DbSet<Conference> Conferences { get; set; }
        public virtual DbSet<PeerReview> PeerReviews { get; set; }
        public virtual DbSet<Rating> Ratings { get; set; }
        public virtual DbSet<ResearchWork> ResearchWorks { get; set; }
        public virtual DbSet<Reviewer> Reviewers { get; set; }
        public virtual DbSet<ReviewerSkill> ReviewerSkills { get; set; }
        public virtual DbSet<Skill> Skills { get; set; }
    }
}
